name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs every midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.pranavjadhav1819 }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{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 }}
